// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkKDi1QuQZ2-B79DZIZ6_7eMfUwSlkrhU',
    appId: '1:369295947925:web:1a0cce45f56653a732c39c',
    messagingSenderId: '369295947925',
    projectId: 'scavengerapp-8edf4',
    authDomain: 'scavengerapp-8edf4.firebaseapp.com',
    storageBucket: 'scavengerapp-8edf4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmS2LkvKwSsWKVXmY-cEUYv809KhNQ-Sk',
    appId: '1:369295947925:android:aa127325847880cb32c39c',
    messagingSenderId: '369295947925',
    projectId: 'scavengerapp-8edf4',
    storageBucket: 'scavengerapp-8edf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCju0Z1p-_lh9XcUD1lsIOlyDXmW9ai5oU',
    appId: '1:369295947925:ios:bea684d6076b524732c39c',
    messagingSenderId: '369295947925',
    projectId: 'scavengerapp-8edf4',
    storageBucket: 'scavengerapp-8edf4.appspot.com',
    iosBundleId: 'com.example.scavengerApp',
  );
}
